/**
 * @license
 * SPDX-License-Identifier: AGPL-3.0
 *
 * 元素周期表数据（118 元素）：
 *   n=原子序数, symbol=元素符号, zh=中文名, en=英文名, mass=相对原子质量,
 *   period=周期, group=族, x/y=周期表坐标(18列), cat=类别(metal/nonmetal/metalloid/noble)
 * 数据源：Periodic-Table-JSON (MIT) + 中国化学会标准中文名
 */

export type ElementCategory = 'metal' | 'nonmetal' | 'metalloid' | 'noble';

export interface ElementInfo {
  n: number;
  symbol: string;
  zh: string;
  en: string;
  mass: number | null;
  /** IUPAC 标准原子量（abridged 中值）；无标准原子量的元素为 null（显示最稳定同位素质量数） */
  massExact?: number | null;
  /** IUPAC 不确定度（如 '0.0002'） */
  massUnc?: string | null;
  /** 无稳定同位素（放射性）：详情卡标注'质量数（无稳定同位素）' */
  radioactive?: boolean;
  period: number;
  group: number | null;
  x: number;
  y: number;
  cat: ElementCategory;
  /** 电子层分布（玻尔模型），如 [2,8,1] */
  shells: number[];
  /** 发现史（简短科普，双语） */
  discovery: { zh: string; en: string };
  /** 生活/现实常见用途（简短科普，双语） */
  usage: { zh: string; en: string };
}

export const ELEMENTS: ElementInfo[] = [
  { n: 1, symbol: 'H', zh: '氢', en: 'Hydrogen', mass: 1, period: 1, group: 1, x: 1, y: 1, cat: 'nonmetal', shells: [1], massExact: 1.008, massUnc: '0.0002', discovery: { zh: '卡文迪许发现。氢（H）是非金属元素。', en: 'Discovered by Henry Cavendish. Hydrogen (H) is a nonmetal.' }, usage: { zh: '氢是宇宙中最丰富的元素，也是水的组成成分，可用作火箭燃料。', en: 'Hydrogen is the most abundant element in the universe, part of water, and used as rocket fuel.' } },
  { n: 2, symbol: 'He', zh: '氦', en: 'Helium', mass: 4.0, period: 1, group: 18, x: 18, y: 1, cat: 'noble', shells: [2], massExact: 4.0026, massUnc: '0.0001', discovery: { zh: '让森与洛基尔通过太阳光谱发现。氦（He）是稀有气体。', en: 'Discovered by Janssen and Lockyer in the solar spectrum. Helium (He) is a noble gas.' }, usage: { zh: '氦常用于充填气球、飞艇，也用于低温超导等尖端领域。', en: 'Helium fills balloons and airships, and is used in cryogenic and superconductor applications.' } },
  { n: 3, symbol: 'Li', zh: '锂', en: 'Lithium', mass: 6.9, period: 2, group: 1, x: 1, y: 2, cat: 'metal', shells: [2,1], massExact: 6.94, massUnc: '0.06', discovery: { zh: '阿尔费德松发现。锂（Li）是金属。', en: 'Discovered by Johan Arfwedson. Lithium (Li) is a metal.' }, usage: { zh: '锂是电池的重要原料，也用于制药（情绪稳定剂）。', en: 'Lithium is key to batteries and is also used in medicine as a mood stabilizer.' } },
  { n: 4, symbol: 'Be', zh: '铍', en: 'Beryllium', mass: 9.0, period: 2, group: 2, x: 2, y: 2, cat: 'metal', shells: [2,2], massExact: 9.0122, massUnc: '0.0001', discovery: { zh: '沃克兰发现。铍（Be）是金属。', en: 'Discovered by Louis Vauquelin. Beryllium (Be) is a metal.' }, usage: { zh: '铍铜合金强度高、耐疲劳，用于精密仪器和航天部件。', en: 'Beryllium-copper alloys are strong and fatigue-resistant, used in precision instruments and aerospace parts.' } },
  { n: 5, symbol: 'B', zh: '硼', en: 'Boron', mass: 10.8, period: 2, group: 13, x: 13, y: 2, cat: 'metalloid', shells: [2,3], massExact: 10.81, massUnc: '0.02', discovery: { zh: '盖-吕萨克与泰纳发现。硼（B）是类金属。', en: 'Discovered by Gay-Lussac and Thénard. Boron (B) is a metalloid.' }, usage: { zh: '硼可作玻璃和陶瓷的原料，硼砂用于洗涤与消毒。', en: 'Boron is used in glass and ceramics; borax is used in cleaning and antiseptics.' } },
  { n: 6, symbol: 'C', zh: '碳', en: 'Carbon', mass: 12, period: 2, group: 14, x: 14, y: 2, cat: 'nonmetal', shells: [2,4], massExact: 12.011, massUnc: '0.002', discovery: { zh: '古埃及已使用。碳（C）是非金属元素。', en: 'Known since ancient Egypt. Carbon (C) is a nonmetal.' }, usage: { zh: '碳是生命的基础元素，煤、石墨、金刚石都是碳的同素异形体。', en: 'Carbon is the basis of life; coal, graphite and diamond are its allotropes.' } },
  { n: 7, symbol: 'N', zh: '氮', en: 'Nitrogen', mass: 14, period: 2, group: 15, x: 15, y: 2, cat: 'nonmetal', shells: [2,5], massExact: 14.007, massUnc: '0.001', discovery: { zh: '卢瑟福发现。氮（N）是非金属元素。', en: 'Discovered by Daniel Rutherford. Nitrogen (N) is a nonmetal.' }, usage: { zh: '氮约占空气体积的 78%，是化肥和炸药的重要原料。', en: 'Nitrogen makes up about 78% of air and is essential for fertilizers and explosives.' } },
  { n: 8, symbol: 'O', zh: '氧', en: 'Oxygen', mass: 16, period: 2, group: 16, x: 16, y: 2, cat: 'nonmetal', shells: [2,6], massExact: 15.999, massUnc: '0.001', discovery: { zh: '舍勒与普里斯特利分别发现。氧（O）是非金属元素。', en: 'Discovered independently by Scheele and Priestley. Oxygen (O) is a nonmetal.' }, usage: { zh: '氧支持燃烧与呼吸，约占空气体积的 21%，医疗急救常用。', en: 'Oxygen supports burning and breathing, makes up about 21% of air, and is vital in medical care.' } },
  { n: 9, symbol: 'F', zh: '氟', en: 'Fluorine', mass: 19.0, period: 2, group: 17, x: 17, y: 2, cat: 'nonmetal', shells: [2,7], massExact: 18.998, massUnc: '0.001', discovery: { zh: '莫瓦桑发现。氟（F）是非金属元素。', en: 'Discovered by Henri Moissan. Fluorine (F) is a nonmetal.' }, usage: { zh: '含氟牙膏能防龋齿，氟化物也用于塑料（如聚四氟乙烯）。', en: 'Fluoride in toothpaste prevents tooth decay; fluorine compounds are used in plastics like PTFE.' } },
  { n: 10, symbol: 'Ne', zh: '氖', en: 'Neon', mass: 20.2, period: 2, group: 18, x: 18, y: 2, cat: 'noble', shells: [2,8], massExact: 20.18, massUnc: '0.001', discovery: { zh: '拉姆齐与特拉弗斯发现。氖（Ne）是稀有气体。', en: 'Discovered by Ramsay and Travers. Neon (Ne) is a noble gas.' }, usage: { zh: '通电时发出红光，常用于霓虹灯招牌。', en: 'Neon glows red when electrified, famous for neon signs.' } },
  { n: 11, symbol: 'Na', zh: '钠', en: 'Sodium', mass: 23, period: 3, group: 1, x: 1, y: 3, cat: 'metal', shells: [2,8,1], massExact: 22.99, massUnc: '0.001', discovery: { zh: '戴维发现。钠（Na）是金属。', en: 'Discovered by Humphry Davy. Sodium (Na) is a metal.' }, usage: { zh: '钠是食盐（氯化钠）的成分，也用于路灯（钠灯）。', en: 'Sodium is part of table salt (NaCl) and is used in street lamps (sodium lamps).' } },
  { n: 12, symbol: 'Mg', zh: '镁', en: 'Magnesium', mass: 24, period: 3, group: 2, x: 2, y: 3, cat: 'metal', shells: [2,8,2], massExact: 24.305, massUnc: '0.002', discovery: { zh: '戴维发现。镁（Mg）是金属。', en: 'Discovered by Humphry Davy. Magnesium (Mg) is a metal.' }, usage: { zh: '镁燃烧发出耀眼白光，用于照明弹和轻质合金。', en: 'Magnesium burns with a brilliant white light, used in flares and lightweight alloys.' } },
  { n: 13, symbol: 'Al', zh: '铝', en: 'Aluminium', mass: 27, period: 3, group: 13, x: 13, y: 3, cat: 'metal', shells: [2,8,3], massExact: 26.982, massUnc: '0.001', discovery: { zh: '1825 年由厄斯泰德制得。铝（Al）是金属。', en: 'First isolated by Ørsted in 1825. Aluminium (Al) is a metal.' }, usage: { zh: '铝质轻耐腐蚀，广泛用于易拉罐、门窗、飞机等。', en: 'Aluminium is light and corrosion-resistant, widely used in cans, windows and aircraft.' } },
  { n: 14, symbol: 'Si', zh: '硅', en: 'Silicon', mass: 28, period: 3, group: 14, x: 14, y: 3, cat: 'metalloid', shells: [2,8,4], massExact: 28.085, massUnc: '0.001', discovery: { zh: '贝采利乌斯发现。硅（Si）是类金属。', en: 'Discovered by Jöns Berzelius. Silicon (Si) is a metalloid.' }, usage: { zh: '硅是芯片与太阳能电池的核心材料，也是地壳中含量第二高的元素。', en: 'Silicon powers chips and solar cells, and is the second most abundant element in Earth\'s crust.' } },
  { n: 15, symbol: 'P', zh: '磷', en: 'Phosphorus', mass: 31, period: 3, group: 15, x: 15, y: 3, cat: 'nonmetal', shells: [2,8,5], massExact: 30.974, massUnc: '0.001', discovery: { zh: '布兰特发现。磷（P）是非金属元素。', en: 'Discovered by Hennig Brand. Phosphorus (P) is a nonmetal.' }, usage: { zh: '磷是骨骼和 DNA 的重要成分，也用于火柴和化肥。', en: 'Phosphorus is vital for bones and DNA, and is used in matches and fertilizers.' } },
  { n: 16, symbol: 'S', zh: '硫', en: 'Sulfur', mass: 32, period: 3, group: 16, x: 16, y: 3, cat: 'nonmetal', shells: [2,8,6], massExact: 32.06, massUnc: '0.02', discovery: { zh: '远古已知。硫（S）是非金属元素。', en: 'Known since ancient times. Sulfur (S) is a nonmetal.' }, usage: { zh: '硫用于制硫酸（工业之母），也用于橡胶硫化。', en: 'Sulfur is used to make sulfuric acid and in rubber vulcanization.' } },
  { n: 17, symbol: 'Cl', zh: '氯', en: 'Chlorine', mass: 35.5, period: 3, group: 17, x: 17, y: 3, cat: 'nonmetal', shells: [2,8,7], massExact: 35.45, massUnc: '0.01', discovery: { zh: '舍勒发现。氯（Cl）是非金属元素。', en: 'Discovered by Carl Scheele. Chlorine (Cl) is a nonmetal.' }, usage: { zh: '氯用于自来水消毒，也用于制造漂白剂和塑料。', en: 'Chlorine disinfects drinking water and is used to make bleach and plastics.' } },
  { n: 18, symbol: 'Ar', zh: '氩', en: 'Argon', mass: 39.9, period: 3, group: 18, x: 18, y: 3, cat: 'noble', shells: [2,8,8], massExact: 39.95, massUnc: '0.16', discovery: { zh: '拉姆齐与特拉弗斯发现。氩（Ar）是稀有气体。', en: 'Discovered by Ramsay and Travers. Argon (Ar) is a noble gas.' }, usage: { zh: '氩化学性质稳定，用于焊接保护气和填充灯泡。', en: 'Argon is inert, used as a shielding gas in welding and to fill light bulbs.' } },
  { n: 19, symbol: 'K', zh: '钾', en: 'Potassium', mass: 39, period: 4, group: 1, x: 1, y: 4, cat: 'metal', shells: [2,8,8,1], massExact: 39.098, massUnc: '0.001', discovery: { zh: '戴维发现。钾（K）是金属。', en: 'Discovered by Humphry Davy. Potassium (K) is a metal.' }, usage: { zh: '钾是植物生长必需元素，钾肥保障农作物产量。', en: 'Potassium is essential for plant growth; potash fertilizers boost crops.' } },
  { n: 20, symbol: 'Ca', zh: '钙', en: 'Calcium', mass: 40, period: 4, group: 2, x: 2, y: 4, cat: 'metal', shells: [2,8,8,2], massExact: 40.078, massUnc: '0.004', discovery: { zh: '戴维发现。钙（Ca）是金属。', en: 'Discovered by Humphry Davy. Calcium (Ca) is a metal.' }, usage: { zh: '钙是骨骼和牙齿的主要成分，也用于建筑（石灰）。', en: 'Calcium builds bones and teeth, and is used in construction as lime.' } },
  { n: 21, symbol: 'Sc', zh: '钪', en: 'Scandium', mass: 45.0, period: 4, group: 3, x: 3, y: 4, cat: 'metal', shells: [2,8,9,2], massExact: 44.956, massUnc: '0.001', discovery: { zh: '由科学家发现。钪（Sc）是金属。', en: 'Discovered by scientists. Scandium (Sc) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 22, symbol: 'Ti', zh: '钛', en: 'Titanium', mass: 47.9, period: 4, group: 4, x: 4, y: 4, cat: 'metal', shells: [2,8,10,2], massExact: 47.867, massUnc: '0.001', discovery: { zh: '由科学家发现。钛（Ti）是金属。', en: 'Discovered by scientists. Titanium (Ti) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 23, symbol: 'V', zh: '钒', en: 'Vanadium', mass: 50.9, period: 4, group: 5, x: 5, y: 4, cat: 'metal', shells: [2,8,11,2], massExact: 50.942, massUnc: '0.001', discovery: { zh: '由科学家发现。钒（V）是金属。', en: 'Discovered by scientists. Vanadium (V) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 24, symbol: 'Cr', zh: '铬', en: 'Chromium', mass: 52.0, period: 4, group: 6, x: 6, y: 4, cat: 'metal', shells: [2,8,13,1], massExact: 51.996, massUnc: '0.001', discovery: { zh: '由科学家发现。铬（Cr）是金属。', en: 'Discovered by scientists. Chromium (Cr) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 25, symbol: 'Mn', zh: '锰', en: 'Manganese', mass: 54.9, period: 4, group: 7, x: 7, y: 4, cat: 'metal', shells: [2,8,13,2], massExact: 54.938, massUnc: '0.001', discovery: { zh: '由科学家发现。锰（Mn）是金属。', en: 'Discovered by scientists. Manganese (Mn) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 26, symbol: 'Fe', zh: '铁', en: 'Iron', mass: 55.8, period: 4, group: 8, x: 8, y: 4, cat: 'metal', shells: [2,8,14,2], massExact: 55.845, massUnc: '0.002', discovery: { zh: '公元前 5000 年已使用。铁（Fe）是金属。', en: 'Used since 5000 BC. Iron (Fe) is a metal.' }, usage: { zh: '铁是应用最广的金属，用于建筑、桥梁、锅具和机械。', en: 'Iron is the most widely used metal, found in buildings, bridges, cookware and machinery.' } },
  { n: 27, symbol: 'Co', zh: '钴', en: 'Cobalt', mass: 58.9, period: 4, group: 9, x: 9, y: 4, cat: 'metal', shells: [2,8,15,2], massExact: 58.933, massUnc: '0.001', discovery: { zh: '由科学家发现。钴（Co）是金属。', en: 'Discovered by scientists. Cobalt (Co) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 28, symbol: 'Ni', zh: '镍', en: 'Nickel', mass: 58.7, period: 4, group: 10, x: 10, y: 4, cat: 'metal', shells: [2,8,16,2], massExact: 58.693, massUnc: '0.001', discovery: { zh: '由科学家发现。镍（Ni）是金属。', en: 'Discovered by scientists. Nickel (Ni) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 29, symbol: 'Cu', zh: '铜', en: 'Copper', mass: 63.5, period: 4, group: 11, x: 11, y: 4, cat: 'metal', shells: [2,8,18,1], massExact: 63.546, massUnc: '0.003', discovery: { zh: '古代中东已使用。铜（Cu）是金属。', en: 'Used since ancient Middle East. Copper (Cu) is a metal.' }, usage: { zh: '铜导电导热性好，广泛用于电线、水管和硬币。', en: 'Copper conducts well, widely used in wires, pipes and coins.' } },
  { n: 30, symbol: 'Zn', zh: '锌', en: 'Zinc', mass: 65.4, period: 4, group: 12, x: 12, y: 4, cat: 'metal', shells: [2,8,18,2], massExact: 65.38, massUnc: '0.02', discovery: { zh: '古代已知。锌（Zn）是金属。', en: 'Known since ancient times. Zinc (Zn) is a metal.' }, usage: { zh: '锌用于镀锌钢板防锈，也是人体必需的微量元素。', en: 'Zinc galvanizes steel against rust and is an essential trace element.' } },
  { n: 31, symbol: 'Ga', zh: '镓', en: 'Gallium', mass: 69.7, period: 4, group: 13, x: 13, y: 4, cat: 'metal', shells: [2,8,18,3], massExact: 69.723, massUnc: '0.001', discovery: { zh: '由科学家发现。镓（Ga）是金属。', en: 'Discovered by scientists. Gallium (Ga) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 32, symbol: 'Ge', zh: '锗', en: 'Germanium', mass: 72.6, period: 4, group: 14, x: 14, y: 4, cat: 'metalloid', shells: [2,8,18,4], massExact: 72.63, massUnc: '0.008', discovery: { zh: '由科学家发现。锗（Ge）是类金属。', en: 'Discovered by scientists. Germanium (Ge) is a metalloid.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 33, symbol: 'As', zh: '砷', en: 'Arsenic', mass: 74.9, period: 4, group: 15, x: 15, y: 4, cat: 'metalloid', shells: [2,8,18,5], massExact: 74.922, massUnc: '0.001', discovery: { zh: '由科学家发现。砷（As）是类金属。', en: 'Discovered by scientists. Arsenic (As) is a metalloid.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 34, symbol: 'Se', zh: '硒', en: 'Selenium', mass: 79.0, period: 4, group: 16, x: 16, y: 4, cat: 'nonmetal', shells: [2,8,18,6], massExact: 78.971, massUnc: '0.008', discovery: { zh: '由科学家发现。硒（Se）是非金属元素。', en: 'Discovered by scientists. Selenium (Se) is a nonmetal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 35, symbol: 'Br', zh: '溴', en: 'Bromine', mass: 79.9, period: 4, group: 17, x: 17, y: 4, cat: 'nonmetal', shells: [2,8,18,7], massExact: 79.904, massUnc: '0.003', discovery: { zh: '由科学家发现。溴（Br）是非金属元素。', en: 'Discovered by scientists. Bromine (Br) is a nonmetal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 36, symbol: 'Kr', zh: '氪', en: 'Krypton', mass: 83.8, period: 4, group: 18, x: 18, y: 4, cat: 'noble', shells: [2,8,18,8], massExact: 83.798, massUnc: '0.002', discovery: { zh: '由科学家发现。氪（Kr）是稀有气体。', en: 'Discovered by scientists. Krypton (Kr) is a noble gas.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 37, symbol: 'Rb', zh: '铷', en: 'Rubidium', mass: 85.5, period: 5, group: 1, x: 1, y: 5, cat: 'metal', shells: [2,8,18,8,1], massExact: 85.468, massUnc: '0.001', discovery: { zh: '由科学家发现。铷（Rb）是金属。', en: 'Discovered by scientists. Rubidium (Rb) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 38, symbol: 'Sr', zh: '锶', en: 'Strontium', mass: 87.6, period: 5, group: 2, x: 2, y: 5, cat: 'metal', shells: [2,8,18,8,2], massExact: 87.62, massUnc: '0.01', discovery: { zh: '由科学家发现。锶（Sr）是金属。', en: 'Discovered by scientists. Strontium (Sr) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 39, symbol: 'Y', zh: '钇', en: 'Yttrium', mass: 88.9, period: 5, group: 3, x: 3, y: 5, cat: 'metal', shells: [2,8,18,9,2], massExact: 88.906, massUnc: '0.001', discovery: { zh: '由科学家发现。钇（Y）是金属。', en: 'Discovered by scientists. Yttrium (Y) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 40, symbol: 'Zr', zh: '锆', en: 'Zirconium', mass: 91.2, period: 5, group: 4, x: 4, y: 5, cat: 'metal', shells: [2,8,18,10,2], massExact: 91.222, massUnc: '0.003', discovery: { zh: '由科学家发现。锆（Zr）是金属。', en: 'Discovered by scientists. Zirconium (Zr) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 41, symbol: 'Nb', zh: '铌', en: 'Niobium', mass: 92.9, period: 5, group: 5, x: 5, y: 5, cat: 'metal', shells: [2,8,18,12,1], massExact: 92.906, massUnc: '0.001', discovery: { zh: '由科学家发现。铌（Nb）是金属。', en: 'Discovered by scientists. Niobium (Nb) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 42, symbol: 'Mo', zh: '钼', en: 'Molybdenum', mass: 96.0, period: 5, group: 6, x: 6, y: 5, cat: 'metal', shells: [2,8,18,13,1], massExact: 95.95, massUnc: '0.01', discovery: { zh: '由科学家发现。钼（Mo）是金属。', en: 'Discovered by scientists. Molybdenum (Mo) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 43, symbol: 'Tc', zh: '锝', en: 'Technetium', mass: 98.0, period: 5, group: 7, x: 7, y: 5, cat: 'metal', shells: [2,8,18,13,2], radioactive: true, discovery: { zh: '由科学家发现。锝（Tc）是金属。', en: 'Discovered by scientists. Technetium (Tc) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 44, symbol: 'Ru', zh: '钌', en: 'Ruthenium', mass: 101.1, period: 5, group: 8, x: 8, y: 5, cat: 'metal', shells: [2,8,18,15,1], massExact: 101.07, massUnc: '0.02', discovery: { zh: '由科学家发现。钌（Ru）是金属。', en: 'Discovered by scientists. Ruthenium (Ru) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 45, symbol: 'Rh', zh: '铑', en: 'Rhodium', mass: 102.9, period: 5, group: 9, x: 9, y: 5, cat: 'metal', shells: [2,8,18,16,1], massExact: 102.91, massUnc: '0.01', discovery: { zh: '由科学家发现。铑（Rh）是金属。', en: 'Discovered by scientists. Rhodium (Rh) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 46, symbol: 'Pd', zh: '钯', en: 'Palladium', mass: 106.4, period: 5, group: 10, x: 10, y: 5, cat: 'metal', shells: [2,8,18,18], massExact: 106.42, massUnc: '0.01', discovery: { zh: '由科学家发现。钯（Pd）是金属。', en: 'Discovered by scientists. Palladium (Pd) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 47, symbol: 'Ag', zh: '银', en: 'Silver', mass: 107.9, period: 5, group: 11, x: 11, y: 5, cat: 'metal', shells: [2,8,18,18,1], massExact: 107.87, massUnc: '0.01', discovery: { zh: '公元前 5000 年前已使用。银（Ag）是金属。', en: 'Used since before 5000 BC. Silver (Ag) is a metal.' }, usage: { zh: '银导电性最好的金属，用于首饰、餐具和电子触点。', en: 'Silver is the best conductor, used in jewelry, cutlery and electronic contacts.' } },
  { n: 48, symbol: 'Cd', zh: '镉', en: 'Cadmium', mass: 112.4, period: 5, group: 12, x: 12, y: 5, cat: 'metal', shells: [2,8,18,18,2], massExact: 112.41, massUnc: '0.01', discovery: { zh: '由科学家发现。镉（Cd）是金属。', en: 'Discovered by scientists. Cadmium (Cd) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 49, symbol: 'In', zh: '铟', en: 'Indium', mass: 114.8, period: 5, group: 13, x: 13, y: 5, cat: 'metal', shells: [2,8,18,18,3], massExact: 114.82, massUnc: '0.01', discovery: { zh: '由科学家发现。铟（In）是金属。', en: 'Discovered by scientists. Indium (In) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 50, symbol: 'Sn', zh: '锡', en: 'Tin', mass: 118.7, period: 5, group: 14, x: 14, y: 5, cat: 'metal', shells: [2,8,18,18,4], massExact: 118.71, massUnc: '0.01', discovery: { zh: '由科学家发现。锡（Sn）是金属。', en: 'Discovered by scientists. Tin (Sn) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 51, symbol: 'Sb', zh: '锑', en: 'Antimony', mass: 121.8, period: 5, group: 15, x: 15, y: 5, cat: 'metalloid', shells: [2,8,18,18,5], massExact: 121.76, massUnc: '0.01', discovery: { zh: '由科学家发现。锑（Sb）是类金属。', en: 'Discovered by scientists. Antimony (Sb) is a metalloid.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 52, symbol: 'Te', zh: '碲', en: 'Tellurium', mass: 127.6, period: 5, group: 16, x: 16, y: 5, cat: 'metalloid', shells: [2,8,18,18,6], massExact: 127.6, massUnc: '0.03', discovery: { zh: '由科学家发现。碲（Te）是类金属。', en: 'Discovered by scientists. Tellurium (Te) is a metalloid.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 53, symbol: 'I', zh: '碘', en: 'Iodine', mass: 126.9, period: 5, group: 17, x: 17, y: 5, cat: 'nonmetal', shells: [2,8,18,18,7], massExact: 126.9, massUnc: '0.01', discovery: { zh: '由科学家发现。碘（I）是非金属元素。', en: 'Discovered by scientists. Iodine (I) is a nonmetal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 54, symbol: 'Xe', zh: '氙', en: 'Xenon', mass: 131.3, period: 5, group: 18, x: 18, y: 5, cat: 'noble', shells: [2,8,18,18,8], massExact: 131.29, massUnc: '0.01', discovery: { zh: '由科学家发现。氙（Xe）是稀有气体。', en: 'Discovered by scientists. Xenon (Xe) is a noble gas.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 55, symbol: 'Cs', zh: '铯', en: 'Cesium', mass: 132.9, period: 6, group: 1, x: 1, y: 6, cat: 'metal', shells: [2,8,18,18,8,1], massExact: 132.91, massUnc: '0.01', discovery: { zh: '由科学家发现。铯（Cs）是金属。', en: 'Discovered by scientists. Cesium (Cs) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 56, symbol: 'Ba', zh: '钡', en: 'Barium', mass: 137.3, period: 6, group: 2, x: 2, y: 6, cat: 'metal', shells: [2,8,18,18,8,2], massExact: 137.33, massUnc: '0.01', discovery: { zh: '由科学家发现。钡（Ba）是金属。', en: 'Discovered by scientists. Barium (Ba) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 57, symbol: 'La', zh: '镧', en: 'Lanthanum', mass: 138.9, period: 6, group: 3, x: 3, y: 9, cat: 'metal', shells: [2,8,18,18,9,2], massExact: 138.91, massUnc: '0.01', discovery: { zh: '由科学家发现。镧（La）是金属。', en: 'Discovered by scientists. Lanthanum (La) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 58, symbol: 'Ce', zh: '铈', en: 'Cerium', mass: 140.1, period: 6, group: 3, x: 4, y: 9, cat: 'metal', shells: [2,8,18,19,9,2], massExact: 140.12, massUnc: '0.01', discovery: { zh: '由科学家发现。铈（Ce）是金属。', en: 'Discovered by scientists. Cerium (Ce) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 59, symbol: 'Pr', zh: '镨', en: 'Praseodymium', mass: 140.9, period: 6, group: 3, x: 5, y: 9, cat: 'metal', shells: [2,8,18,21,8,2], massExact: 140.91, massUnc: '0.01', discovery: { zh: '由科学家发现。镨（Pr）是金属。', en: 'Discovered by scientists. Praseodymium (Pr) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 60, symbol: 'Nd', zh: '钕', en: 'Neodymium', mass: 144.2, period: 6, group: 3, x: 6, y: 9, cat: 'metal', shells: [2,8,18,22,8,2], massExact: 144.24, massUnc: '0.01', discovery: { zh: '由科学家发现。钕（Nd）是金属。', en: 'Discovered by scientists. Neodymium (Nd) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 61, symbol: 'Pm', zh: '钷', en: 'Promethium', mass: 145.0, period: 6, group: 3, x: 7, y: 9, cat: 'metal', shells: [2,8,18,23,8,2], radioactive: true, discovery: { zh: '由科学家发现。钷（Pm）是金属。', en: 'Discovered by scientists. Promethium (Pm) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 62, symbol: 'Sm', zh: '钐', en: 'Samarium', mass: 150.4, period: 6, group: 3, x: 8, y: 9, cat: 'metal', shells: [2,8,18,24,8,2], massExact: 150.36, massUnc: '0.02', discovery: { zh: '由科学家发现。钐（Sm）是金属。', en: 'Discovered by scientists. Samarium (Sm) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 63, symbol: 'Eu', zh: '铕', en: 'Europium', mass: 152.0, period: 6, group: 3, x: 9, y: 9, cat: 'metal', shells: [2,8,18,25,8,2], massExact: 151.96, massUnc: '0.01', discovery: { zh: '由科学家发现。铕（Eu）是金属。', en: 'Discovered by scientists. Europium (Eu) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 64, symbol: 'Gd', zh: '钆', en: 'Gadolinium', mass: 157.3, period: 6, group: 3, x: 10, y: 9, cat: 'metal', shells: [2,8,18,25,9,2], massExact: 157.25, massUnc: '0.01', discovery: { zh: '由科学家发现。钆（Gd）是金属。', en: 'Discovered by scientists. Gadolinium (Gd) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 65, symbol: 'Tb', zh: '铽', en: 'Terbium', mass: 158.9, period: 6, group: 3, x: 11, y: 9, cat: 'metal', shells: [2,8,18,27,8,2], massExact: 158.93, massUnc: '0.01', discovery: { zh: '由科学家发现。铽（Tb）是金属。', en: 'Discovered by scientists. Terbium (Tb) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 66, symbol: 'Dy', zh: '镝', en: 'Dysprosium', mass: 162.5, period: 6, group: 3, x: 12, y: 9, cat: 'metal', shells: [2,8,18,28,8,2], massExact: 162.5, massUnc: '0.01', discovery: { zh: '由科学家发现。镝（Dy）是金属。', en: 'Discovered by scientists. Dysprosium (Dy) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 67, symbol: 'Ho', zh: '钬', en: 'Holmium', mass: 164.9, period: 6, group: 3, x: 13, y: 9, cat: 'metal', shells: [2,8,18,29,8,2], massExact: 164.93, massUnc: '0.01', discovery: { zh: '由科学家发现。钬（Ho）是金属。', en: 'Discovered by scientists. Holmium (Ho) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 68, symbol: 'Er', zh: '铒', en: 'Erbium', mass: 167.3, period: 6, group: 3, x: 14, y: 9, cat: 'metal', shells: [2,8,18,30,8,2], massExact: 167.26, massUnc: '0.01', discovery: { zh: '由科学家发现。铒（Er）是金属。', en: 'Discovered by scientists. Erbium (Er) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 69, symbol: 'Tm', zh: '铥', en: 'Thulium', mass: 168.9, period: 6, group: 3, x: 15, y: 9, cat: 'metal', shells: [2,8,18,31,8,2], massExact: 168.93, massUnc: '0.01', discovery: { zh: '由科学家发现。铥（Tm）是金属。', en: 'Discovered by scientists. Thulium (Tm) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 70, symbol: 'Yb', zh: '镱', en: 'Ytterbium', mass: 173.0, period: 6, group: 3, x: 16, y: 9, cat: 'metal', shells: [2,8,18,32,8,2], massExact: 173.05, massUnc: '0.02', discovery: { zh: '由科学家发现。镱（Yb）是金属。', en: 'Discovered by scientists. Ytterbium (Yb) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 71, symbol: 'Lu', zh: '镥', en: 'Lutetium', mass: 175.0, period: 6, group: 3, x: 17, y: 9, cat: 'metal', shells: [2,8,18,32,9,2], massExact: 174.97, massUnc: '0.01', discovery: { zh: '由科学家发现。镥（Lu）是金属。', en: 'Discovered by scientists. Lutetium (Lu) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 72, symbol: 'Hf', zh: '铪', en: 'Hafnium', mass: 178.5, period: 6, group: 4, x: 4, y: 6, cat: 'metal', shells: [2,8,18,32,10,2], massExact: 178.49, massUnc: '0.01', discovery: { zh: '由科学家发现。铪（Hf）是金属。', en: 'Discovered by scientists. Hafnium (Hf) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 73, symbol: 'Ta', zh: '钽', en: 'Tantalum', mass: 180.9, period: 6, group: 5, x: 5, y: 6, cat: 'metal', shells: [2,8,18,32,11,2], massExact: 180.95, massUnc: '0.01', discovery: { zh: '由科学家发现。钽（Ta）是金属。', en: 'Discovered by scientists. Tantalum (Ta) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 74, symbol: 'W', zh: '钨', en: 'Tungsten', mass: 183.8, period: 6, group: 6, x: 6, y: 6, cat: 'metal', shells: [2,8,18,32,12,2], massExact: 183.84, massUnc: '0.01', discovery: { zh: '由科学家发现。钨（W）是金属。', en: 'Discovered by scientists. Tungsten (W) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 75, symbol: 'Re', zh: '铼', en: 'Rhenium', mass: 186.2, period: 6, group: 7, x: 7, y: 6, cat: 'metal', shells: [2,8,18,32,13,2], massExact: 186.21, massUnc: '0.01', discovery: { zh: '由科学家发现。铼（Re）是金属。', en: 'Discovered by scientists. Rhenium (Re) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 76, symbol: 'Os', zh: '锇', en: 'Osmium', mass: 190.2, period: 6, group: 8, x: 8, y: 6, cat: 'metal', shells: [2,8,18,32,14,2], massExact: 190.23, massUnc: '0.03', discovery: { zh: '由科学家发现。锇（Os）是金属。', en: 'Discovered by scientists. Osmium (Os) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 77, symbol: 'Ir', zh: '铱', en: 'Iridium', mass: 192.2, period: 6, group: 9, x: 9, y: 6, cat: 'metal', shells: [2,8,18,32,15,2], massExact: 192.22, massUnc: '0.01', discovery: { zh: '由科学家发现。铱（Ir）是金属。', en: 'Discovered by scientists. Iridium (Ir) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 78, symbol: 'Pt', zh: '铂', en: 'Platinum', mass: 195.1, period: 6, group: 10, x: 10, y: 6, cat: 'metal', shells: [2,8,18,32,17,1], massExact: 195.08, massUnc: '0.02', discovery: { zh: '由科学家发现。铂（Pt）是金属。', en: 'Discovered by scientists. Platinum (Pt) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 79, symbol: 'Au', zh: '金', en: 'Gold', mass: 197.0, period: 6, group: 11, x: 11, y: 6, cat: 'metal', shells: [2,8,18,32,18,1], massExact: 196.97, massUnc: '0.01', discovery: { zh: '古代中东已使用。金（Au）是金属。', en: 'Used since ancient Middle East. Gold (Au) is a metal.' }, usage: { zh: '金化学性质稳定，用于首饰、货币储备和电子元件。', en: 'Gold is chemically stable, used in jewelry, currency reserves and electronics.' } },
  { n: 80, symbol: 'Hg', zh: '汞', en: 'Mercury', mass: 200.6, period: 6, group: 12, x: 12, y: 6, cat: 'metal', shells: [2,8,18,32,18,2], massExact: 200.59, massUnc: '0.01', discovery: { zh: '古代已知。汞（Hg）是金属。', en: 'Known since ancient times. Mercury (Hg) is a metal.' }, usage: { zh: '汞是常温下唯一的液态金属，曾用于温度计（现多禁用）。', en: 'Mercury is the only liquid metal at room temperature, once used in thermometers (now restricted).' } },
  { n: 81, symbol: 'Tl', zh: '铊', en: 'Thallium', mass: 204.4, period: 6, group: 13, x: 13, y: 6, cat: 'metal', shells: [2,8,18,32,18,3], massExact: 204.38, massUnc: '0.01', discovery: { zh: '由科学家发现。铊（Tl）是金属。', en: 'Discovered by scientists. Thallium (Tl) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 82, symbol: 'Pb', zh: '铅', en: 'Lead', mass: 207.2, period: 6, group: 14, x: 14, y: 6, cat: 'metal', shells: [2,8,18,32,18,4], massExact: 207.2, massUnc: '1.1', discovery: { zh: '古代中东已使用。铅（Pb）是金属。', en: 'Used since ancient Middle East. Lead (Pb) is a metal.' }, usage: { zh: '铅用于电池和防辐射材料（含铅涂料已受限）。', en: 'Lead is used in batteries and radiation shielding (lead paint is now restricted).' } },
  { n: 83, symbol: 'Bi', zh: '铋', en: 'Bismuth', mass: 209.0, period: 6, group: 15, x: 15, y: 6, cat: 'metal', shells: [2,8,18,32,18,5], massExact: 208.98, massUnc: '0.01', discovery: { zh: '由科学家发现。铋（Bi）是金属。', en: 'Discovered by scientists. Bismuth (Bi) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 84, symbol: 'Po', zh: '钋', en: 'Polonium', mass: 209.0, period: 6, group: 16, x: 16, y: 6, cat: 'metal', shells: [2,8,18,32,18,6], radioactive: true, discovery: { zh: '由科学家发现。钋（Po）是金属。', en: 'Discovered by scientists. Polonium (Po) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 85, symbol: 'At', zh: '砹', en: 'Astatine', mass: 210.0, period: 6, group: 17, x: 17, y: 6, cat: 'metalloid', shells: [2,8,18,32,18,7], radioactive: true, discovery: { zh: '由科学家发现。砹（At）是类金属。', en: 'Discovered by scientists. Astatine (At) is a metalloid.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 86, symbol: 'Rn', zh: '氡', en: 'Radon', mass: 222.0, period: 6, group: 18, x: 18, y: 6, cat: 'noble', shells: [2,8,18,32,18,8], radioactive: true, discovery: { zh: '由科学家发现。氡（Rn）是稀有气体。', en: 'Discovered by scientists. Radon (Rn) is a noble gas.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 87, symbol: 'Fr', zh: '钫', en: 'Francium', mass: 223.0, period: 7, group: 1, x: 1, y: 7, cat: 'metal', shells: [2,8,18,32,18,8,1], radioactive: true, discovery: { zh: '由科学家发现。钫（Fr）是金属。', en: 'Discovered by scientists. Francium (Fr) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 88, symbol: 'Ra', zh: '镭', en: 'Radium', mass: 226.0, period: 7, group: 2, x: 2, y: 7, cat: 'metal', shells: [2,8,18,32,18,8,2], radioactive: true, discovery: { zh: '由科学家发现。镭（Ra）是金属。', en: 'Discovered by scientists. Radium (Ra) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 89, symbol: 'Ac', zh: '锕', en: 'Actinium', mass: 227.0, period: 7, group: 3, x: 3, y: 10, cat: 'metal', shells: [2,8,18,32,18,9,2], radioactive: true, discovery: { zh: '由科学家发现。锕（Ac）是金属。', en: 'Discovered by scientists. Actinium (Ac) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 90, symbol: 'Th', zh: '钍', en: 'Thorium', mass: 232.0, period: 7, group: 3, x: 4, y: 10, cat: 'metal', shells: [2,8,18,32,18,10,2], massExact: 232.04, massUnc: '0.01', discovery: { zh: '由科学家发现。钍（Th）是金属。', en: 'Discovered by scientists. Thorium (Th) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 91, symbol: 'Pa', zh: '镤', en: 'Protactinium', mass: 231.0, period: 7, group: 3, x: 5, y: 10, cat: 'metal', shells: [2,8,18,32,20,9,2], massExact: 231.04, massUnc: '0.01', discovery: { zh: '由科学家发现。镤（Pa）是金属。', en: 'Discovered by scientists. Protactinium (Pa) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 92, symbol: 'U', zh: '铀', en: 'Uranium', mass: 238.0, period: 7, group: 3, x: 6, y: 10, cat: 'metal', shells: [2,8,18,32,21,9,2], massExact: 238.03, massUnc: '0.01', discovery: { zh: '克拉普罗特发现。铀（U）是金属。', en: 'Discovered by Martin Klaproth. Uranium (U) is a metal.' }, usage: { zh: '铀是核电站的重要燃料，也用于核医学。', en: 'Uranium fuels nuclear power plants and is used in nuclear medicine.' } },
  { n: 93, symbol: 'Np', zh: '镎', en: 'Neptunium', mass: 237.0, period: 7, group: 3, x: 7, y: 10, cat: 'metal', shells: [2,8,18,32,22,9,2], radioactive: true, discovery: { zh: '由科学家发现。镎（Np）是金属。', en: 'Discovered by scientists. Neptunium (Np) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 94, symbol: 'Pu', zh: '钚', en: 'Plutonium', mass: 244.0, period: 7, group: 3, x: 8, y: 10, cat: 'metal', shells: [2,8,18,32,24,8,2], radioactive: true, discovery: { zh: '由科学家发现。钚（Pu）是金属。', en: 'Discovered by scientists. Plutonium (Pu) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 95, symbol: 'Am', zh: '镅', en: 'Americium', mass: 243.0, period: 7, group: 3, x: 9, y: 10, cat: 'metal', shells: [2,8,18,32,25,8,2], radioactive: true, discovery: { zh: '由科学家发现。镅（Am）是金属。', en: 'Discovered by scientists. Americium (Am) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 96, symbol: 'Cm', zh: '锔', en: 'Curium', mass: 247.0, period: 7, group: 3, x: 10, y: 10, cat: 'metal', shells: [2,8,18,32,25,9,2], radioactive: true, discovery: { zh: '由科学家发现。锔（Cm）是金属。', en: 'Discovered by scientists. Curium (Cm) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 97, symbol: 'Bk', zh: '锫', en: 'Berkelium', mass: 247.0, period: 7, group: 3, x: 11, y: 10, cat: 'metal', shells: [2,8,18,32,27,8,2], radioactive: true, discovery: { zh: '由科学家发现。锫（Bk）是金属。', en: 'Discovered by scientists. Berkelium (Bk) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 98, symbol: 'Cf', zh: '锎', en: 'Californium', mass: 251.0, period: 7, group: 3, x: 12, y: 10, cat: 'metal', shells: [2,8,18,32,28,8,2], radioactive: true, discovery: { zh: '由科学家发现。锎（Cf）是金属。', en: 'Discovered by scientists. Californium (Cf) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 99, symbol: 'Es', zh: '锿', en: 'Einsteinium', mass: 252.0, period: 7, group: 3, x: 13, y: 10, cat: 'metal', shells: [2,8,18,32,29,8,2], radioactive: true, discovery: { zh: '由科学家发现。锿（Es）是金属。', en: 'Discovered by scientists. Einsteinium (Es) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 100, symbol: 'Fm', zh: '镄', en: 'Fermium', mass: 257.0, period: 7, group: 3, x: 14, y: 10, cat: 'metal', shells: [2,8,18,32,30,8,2], radioactive: true, discovery: { zh: '由科学家发现。镄（Fm）是金属。', en: 'Discovered by scientists. Fermium (Fm) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 101, symbol: 'Md', zh: '钔', en: 'Mendelevium', mass: 258.0, period: 7, group: 3, x: 15, y: 10, cat: 'metal', shells: [2,8,18,32,31,8,2], radioactive: true, discovery: { zh: '由科学家发现。钔（Md）是金属。', en: 'Discovered by scientists. Mendelevium (Md) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 102, symbol: 'No', zh: '锘', en: 'Nobelium', mass: 259.0, period: 7, group: 3, x: 16, y: 10, cat: 'metal', shells: [2,8,18,32,32,8,2], radioactive: true, discovery: { zh: '由科学家发现。锘（No）是金属。', en: 'Discovered by scientists. Nobelium (No) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 103, symbol: 'Lr', zh: '铹', en: 'Lawrencium', mass: 266.0, period: 7, group: 3, x: 17, y: 10, cat: 'metal', shells: [2,8,18,32,32,8,3], radioactive: true, discovery: { zh: '由科学家发现。铹（Lr）是金属。', en: 'Discovered by scientists. Lawrencium (Lr) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 104, symbol: 'Rf', zh: '𬬻', en: 'Rutherfordium', mass: 267.0, period: 7, group: 4, x: 4, y: 7, cat: 'metal', shells: [2,8,18,32,32,10,2], radioactive: true, discovery: { zh: '由科学家发现。𬬻（Rf）是金属。', en: 'Discovered by scientists. Rutherfordium (Rf) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 105, symbol: 'Db', zh: '𬭊', en: 'Dubnium', mass: 268.0, period: 7, group: 5, x: 5, y: 7, cat: 'metal', shells: [2,8,18,32,32,11,2], radioactive: true, discovery: { zh: '由科学家发现。𬭊（Db）是金属。', en: 'Discovered by scientists. Dubnium (Db) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 106, symbol: 'Sg', zh: '𬭳', en: 'Seaborgium', mass: 269.0, period: 7, group: 6, x: 6, y: 7, cat: 'metal', shells: [2,8,18,32,32,12,2], radioactive: true, discovery: { zh: '由科学家发现。𬭳（Sg）是金属。', en: 'Discovered by scientists. Seaborgium (Sg) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 107, symbol: 'Bh', zh: '𬭛', en: 'Bohrium', mass: 270.0, period: 7, group: 7, x: 7, y: 7, cat: 'metal', shells: [2,8,18,32,32,13,2], radioactive: true, discovery: { zh: '由科学家发现。𬭛（Bh）是金属。', en: 'Discovered by scientists. Bohrium (Bh) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 108, symbol: 'Hs', zh: '𬭶', en: 'Hassium', mass: 277, period: 7, group: 8, x: 8, y: 7, cat: 'metal', shells: [2,8,18,32,32,14,2], radioactive: true, discovery: { zh: '由科学家发现。𬭶（Hs）是金属。', en: 'Discovered by scientists. Hassium (Hs) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 109, symbol: 'Mt', zh: '鿏', en: 'Meitnerium', mass: 278.0, period: 7, group: 9, x: 9, y: 7, cat: 'metal', shells: [2,8,18,32,32,15,2], radioactive: true, discovery: { zh: '由科学家发现。鿏（Mt）是金属。', en: 'Discovered by scientists. Meitnerium (Mt) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 110, symbol: 'Ds', zh: '𫟼', en: 'Darmstadtium', mass: 281.0, period: 7, group: 10, x: 10, y: 7, cat: 'metal', shells: [2,8,18,32,32,16,2], radioactive: true, discovery: { zh: '由科学家发现。𫟼（Ds）是金属。', en: 'Discovered by scientists. Darmstadtium (Ds) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 111, symbol: 'Rg', zh: '𬬭', en: 'Roentgenium', mass: 282.0, period: 7, group: 11, x: 11, y: 7, cat: 'metal', shells: [2,8,18,32,32,17,2], radioactive: true, discovery: { zh: '由科学家发现。𬬭（Rg）是金属。', en: 'Discovered by scientists. Roentgenium (Rg) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 112, symbol: 'Cn', zh: '鿔', en: 'Copernicium', mass: 285.0, period: 7, group: 12, x: 12, y: 7, cat: 'metal', shells: [2,8,18,32,32,18,2], radioactive: true, discovery: { zh: '由科学家发现。鿔（Cn）是金属。', en: 'Discovered by scientists. Copernicium (Cn) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 113, symbol: 'Nh', zh: '鿭', en: 'Nihonium', mass: 286.0, period: 7, group: 13, x: 13, y: 7, cat: 'metal', shells: [2,8,18,32,32,18,3], radioactive: true, discovery: { zh: '由科学家发现。鿭（Nh）是金属。', en: 'Discovered by scientists. Nihonium (Nh) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 114, symbol: 'Fl', zh: '𫓧', en: 'Flerovium', mass: 289.0, period: 7, group: 14, x: 14, y: 7, cat: 'metal', shells: [2,8,18,32,32,18,4], radioactive: true, discovery: { zh: '由科学家发现。𫓧（Fl）是金属。', en: 'Discovered by scientists. Flerovium (Fl) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 115, symbol: 'Mc', zh: '镆', en: 'Moscovium', mass: 290, period: 7, group: 15, x: 15, y: 7, cat: 'metal', shells: [2,8,18,32,32,18,5], radioactive: true, discovery: { zh: '由科学家发现。镆（Mc）是金属。', en: 'Discovered by scientists. Moscovium (Mc) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 116, symbol: 'Lv', zh: '𫟷', en: 'Livermorium', mass: 293.0, period: 7, group: 16, x: 16, y: 7, cat: 'metal', shells: [2,8,18,32,32,18,6], radioactive: true, discovery: { zh: '由科学家发现。𫟷（Lv）是金属。', en: 'Discovered by scientists. Livermorium (Lv) is a metal.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 117, symbol: 'Ts', zh: '鿬', en: 'Tennessine', mass: 294.0, period: 7, group: 17, x: 17, y: 7, cat: 'nonmetal', shells: [2,8,18,32,32,18,7], radioactive: true, discovery: { zh: '由科学家发现。鿬（Ts）是类金属。', en: 'Discovered by scientists. Tennessine (Ts) is a metalloid.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
  { n: 118, symbol: 'Og', zh: '鿫', en: 'Oganesson', mass: 294.0, period: 7, group: 18, x: 18, y: 7, cat: 'noble', shells: [2,8,18,32,32,18,8], radioactive: true, discovery: { zh: '由科学家发现。鿫（Og）是稀有气体。', en: 'Discovered by scientists. Oganesson (Og) is a noble gas.' }, usage: { zh: '在工业生产和科学研究中具有重要用途。', en: 'It has important uses in industry and scientific research.' } },
];

/** 按原子序数快速索引 */
export const elementByNumber = new Map<number, ElementInfo>(ELEMENTS.map((e) => [e.n, e]));
