/**
 * @license
 * SPDX-License-Identifier: AGPL-3.0
 *
 * 物理公式数据（初中苏科版）。
 * 依据：physics_kb references/formula_sheet.md（苏科版八下+九上）逐章提炼，
 * 公式、单位、适用条件对照教材；relatedConstants 关联常量页符号（双向跳转）。
 * category: mech 力学 / thermal 热学 / optics 光学 / sound 声学 / elec 电学（与常量页一致）。
 */
export type PhysicsFormulaCategory = 'mech' | 'thermal' | 'optics' | 'sound' | 'elec';

export interface PhysicsFormula {
  /** 唯一 id（供常量反链跳转） */
  id: string;
  name: { zh: string; en: string };
  /** KaTeX 公式 */
  formula: string;
  /** 中文说明（教材表述） */
  label: { zh: string; en: string };
  category: PhysicsFormulaCategory;
  /** 单位（结果） */
  unit: string;
  /** 适用条件 */
  condition: { zh: string; en: string };
  /** 常考易错 */
  pitfall: { zh: string; en: string };
  /** 应用场景 */
  usage: { zh: string; en: string };
  /** 教材章节（苏科版） */
  chapter: string;
  /** 关联常量符号（跳转常量页；同名多值时匹配全部） */
  relatedConstants?: string[];
  /** 关联实验 id（可选） */
  labId?: string;
  /** 配图类型（可选，教科书示意图） */
  diagram?: { kind: string };
}

export const PHYSICS_FORMULA_CATEGORY_ZH: Record<PhysicsFormulaCategory, string> = {
  mech: '力学',
  thermal: '热学',
  optics: '光学',
  sound: '声学',
  elec: '电学',
};

export const PHYSICS_FORMULA_CATEGORY_EN: Record<PhysicsFormulaCategory, string> = {
  mech: 'Mechanics',
  thermal: 'Thermal',
  optics: 'Optics',
  sound: 'Sound',
  elec: 'Electricity',
};

export const PHYSICS_FORMULAS: PhysicsFormula[] = [
  // ── 力学 ──
  {
    id: 'speed',
    name: { zh: '速度', en: 'Speed' },
    formula: 'v = \\frac{s}{t}',
    label: { zh: '速度等于路程除以时间，v = s/t', en: 'Speed equals distance divided by time.' },
    category: 'mech',
    unit: 'm/s',
    condition: { zh: '匀速直线运动或求平均速度；s 为通过的路程，t 为所用时间。', en: 'Uniform motion or average speed; s is distance, t is time.' },
    pitfall: { zh: '平均速度 = 总路程 ÷ 总时间，不是速度的平均值；单位换算 1 m/s = 3.6 km/h。', en: 'Average speed uses total distance over total time, not the mean of speeds; 1 m/s = 3.6 km/h.' },
    usage: { zh: '运动快慢比较、回声测距、列车时刻表问题。', en: 'Comparing motion, echo ranging, timetable problems.' },
    chapter: '第五章 物体的运动',
  },
  {
    id: 'density',
    name: { zh: '密度', en: 'Density' },
    formula: '\\rho = \\frac{m}{V}',
    label: { zh: '密度等于质量除以体积，ρ = m/V', en: 'Density equals mass divided by volume.' },
    category: 'mech',
    unit: 'kg/m³',
    condition: { zh: '同种物质密度不变（温度、状态一定时）；1 g/cm³ = 1×10³ kg/m³。', en: 'Density is a property of the substance; 1 g/cm³ = 1×10³ kg/m³.' },
    pitfall: { zh: '密度是物质属性，不随质量、体积改变；鉴别物质时需查密度表。', en: 'Density is intrinsic; do not scale it with mass or volume.' },
    usage: { zh: '鉴别物质、空心实心判断、质量体积换算。', en: 'Identifying substances, hollow vs solid, conversions.' },
    chapter: '第六章 物质的物理属性',
    relatedConstants: ['ρ水'],
  },
  {
    id: 'gravity',
    name: { zh: '重力', en: 'Weight' },
    formula: 'G = mg',
    label: { zh: '重力等于质量乘以重力常数，G = mg', en: 'Weight equals mass times gravitational acceleration.' },
    category: 'mech',
    unit: 'N',
    condition: { zh: 'g 取 9.8 N/kg（粗略计算可取 10 N/kg）；重力方向竖直向下。', en: 'g ≈ 9.8 N/kg (often 10 N/kg); gravity points downward.' },
    pitfall: { zh: '质量是属性、重力是力：同一物体在地球不同位置 g 略变，质量不变。', en: 'Mass is intrinsic; weight varies with g.' },
    usage: { zh: '求物体重力、由重力求质量。', en: 'Finding weight from mass and vice versa.' },
    chapter: '第七章 力',
    diagram: { kind: 'gravity' },
    relatedConstants: ['g'],
    labId: 'pressure',
  },
  {
    id: 'pressure',
    name: { zh: '压强', en: 'Pressure' },
    formula: 'p = \\frac{F}{S}',
    label: { zh: '压强等于压力除以受力面积，p = F/S', en: 'Pressure equals force divided by area.' },
    category: 'mech',
    unit: 'Pa',
    condition: { zh: 'F 为垂直压在物体表面上的压力，S 为受力面积（接触面积）。', en: 'F is the force perpendicular to the surface; S is the contact area.' },
    pitfall: { zh: '压力不一定等于重力；受力面积取实际接触面积（如双脚→单脚）。', en: 'Pressure is not always weight; use the actual contact area.' },
    usage: { zh: '压强的增大与减小（刀口锋利、书包带宽）、压强计算。', en: 'Increasing/reducing pressure; pressure calculations.' },
    chapter: '第九章 压强和浮力',
    diagram: { kind: 'pressure' },
    labId: 'pressure',
  },
  {
    id: 'liquid-pressure',
    name: { zh: '液体压强', en: 'Liquid pressure' },
    formula: 'p = \\rho g h',
    label: { zh: '液体内部压强等于液体密度×重力常数×深度，p = ρgh', en: 'Liquid pressure equals ρgh at depth h.' },
    category: 'mech',
    unit: 'Pa',
    condition: { zh: 'h 为从液面到该点的竖直深度；只适用于静止液体内部。', en: 'h is the vertical depth below the surface; static liquids only.' },
    pitfall: { zh: '液体压强与液体体积、容器形状无关，只与 ρ 和 h 有关。', en: 'Liquid pressure depends only on ρ and h, not on volume or vessel shape.' },
    usage: { zh: '水坝上窄下宽、潜水深度、连通器原理。', en: 'Dams, diving depth, communicating vessels.' },
    chapter: '第九章 压强和浮力',
    diagram: { kind: 'liquid-pressure' },
    relatedConstants: ['ρ水', 'g'],
  },
  {
    id: 'buoyancy',
    name: { zh: '阿基米德原理', en: "Archimedes' principle" },
    formula: 'F_\\text{浮} = G_\\text{排} = \\rho_\\text{液} g V_\\text{排}',
    label: { zh: '浮力等于排开液体所受的重力，F浮 = ρ液 g V排', en: 'Buoyant force equals the weight of displaced fluid.' },
    category: 'mech',
    unit: 'N',
    condition: { zh: '浸在液体（或气体）中的物体；V排 为排开液体的体积。', en: 'Body immersed in fluid; V_displaced is the displaced volume.' },
    pitfall: { zh: '浮力与物体自身密度、形状、浸没深度无关；漂浮时 V排 小于 V物。', en: 'Buoyancy ignores the body\'s own density, shape, or depth; floating means V_displaced < V_body.' },
    usage: { zh: '轮船吃水、潜水艇、密度计、浮沉条件判断。', en: 'Ships, submarines, hydrometers, sinking/floating conditions.' },
    chapter: '第九章 压强和浮力',
    diagram: { kind: 'buoyancy' },
    relatedConstants: ['ρ水', 'ρ酒精', 'g'],
    labId: 'buoyancy',
  },
  {
    id: 'buoyancy-weighing',
    name: { zh: '称重法测浮力', en: 'Buoyancy by weighing' },
    formula: 'F_\\text{浮} = G - F_\\text{示}',
    label: { zh: '称重法：浮力等于空气中的重力减去浸入液体后测力计示数', en: 'Buoyancy = weight in air minus spring-scale reading in liquid.' },
    category: 'mech',
    unit: 'N',
    condition: { zh: '物体用测力计吊着浸入液体中（不接触容器底）。', en: 'Body suspended from a spring scale, not touching the container.' },
    pitfall: { zh: 'F示 是浸入后测力计读数，不是物体的重力。', en: 'F_reading is the scale reading while submerged, not the weight.' },
    usage: { zh: '实验室测浮力、结合阿基米德原理求液体密度。', en: 'Lab buoyancy measurement; finding liquid density.' },
    chapter: '第九章 压强和浮力',
    relatedConstants: ['g'],
    labId: 'buoyancy',
  },
  {
    id: 'lever',
    name: { zh: '杠杆平衡条件', en: 'Lever balance' },
    formula: 'F_1 l_1 = F_2 l_2',
    label: { zh: '杠杆平衡时动力×动力臂 = 阻力×阻力臂，F₁l₁ = F₂l₂', en: 'At balance, effort × effort arm = load × load arm.' },
    category: 'mech',
    unit: '—',
    condition: { zh: '杠杆静止或匀速转动时；l 为支点到力的作用线的垂直距离。', en: 'Lever at rest or rotating uniformly; l is the perpendicular distance to the fulcrum.' },
    pitfall: { zh: '力臂是支点到力的作用线的垂直距离，不是支点到作用点的距离。', en: 'The arm is the perpendicular distance, not the direct distance.' },
    usage: { zh: '省力/费力杠杆判断、天平原理、撬棒与船桨。', en: 'Effort-saving levers, balance principle, crowbars and oars.' },
    chapter: '第十一章 简单机械和功',
    diagram: { kind: 'lever' },
    labId: 'lever',
  },
  {
    id: 'work',
    name: { zh: '功', en: 'Work' },
    formula: 'W = Fs',
    label: { zh: '功等于力乘以沿力方向移动的距离，W = Fs', en: 'Work equals force times distance along the force.' },
    category: 'mech',
    unit: 'J',
    condition: { zh: '有力作用在物体上且物体沿力的方向移动了距离。', en: 'A force acts and the body moves along its direction.' },
    pitfall: { zh: '「劳而无功」：有力无距离、有距离无力、力与距离垂直都不做功。', en: 'No work without displacement along the force (e.g. perpendicular).' },
    usage: { zh: '判断是否做功、计算功的大小。', en: 'Judging and computing work.' },
    chapter: '第十一章 简单机械和功',
  },
  {
    id: 'power',
    name: { zh: '功率', en: 'Power' },
    formula: 'P = \\frac{W}{t}',
    label: { zh: '功率等于功除以时间，P = W/t；也等于力乘以速度 P = Fv', en: 'Power equals work over time; also P = Fv.' },
    category: 'mech',
    unit: 'W',
    condition: { zh: 'P = Fv 适用于力与速度同方向（如匀速牵引）。', en: 'P = Fv applies when force and velocity align.' },
    pitfall: { zh: '功率表示做功快慢，不是做功多少；单位 1 kW = 1000 W。', en: 'Power measures how fast work is done, not the total work.' },
    usage: { zh: '机械做功快慢比较、汽车功率与牵引力问题。', en: 'Comparing machines; car power and traction.' },
    chapter: '第十一章 简单机械和功',
  },
  {
    id: 'efficiency',
    name: { zh: '机械效率', en: 'Mechanical efficiency' },
    formula: '\\eta = \\frac{W_\\text{有}}{W_\\text{总}} \\times 100\\%',
    label: { zh: '机械效率等于有用功除以总功，η = W有/W总', en: 'Efficiency equals useful work over total work.' },
    category: 'mech',
    unit: '%',
    condition: { zh: '有用功 W有 = Gh（竖直提升），总功 W总 = Fs（拉力做功）。', en: 'Useful work W_useful = Gh; total work W_total = Fs.' },
    pitfall: { zh: '机械效率永远小于 1（有额外功）；不是功率，与省力与否无关。', en: 'Efficiency is always < 1 and is not power.' },
    usage: { zh: '滑轮组、斜面、起重机效率计算。', en: 'Pulley systems, inclined planes, cranes.' },
    chapter: '第十一章 简单机械和功',
    relatedConstants: ['g'],
  },
  {
    id: 'kinetic-energy',
    name: { zh: '动能', en: 'Kinetic energy' },
    formula: 'E_\\text{k} = \\frac{1}{2} m v^2',
    label: { zh: '动能等于二分之一质量乘以速度的平方，Ek = ½mv²', en: 'Kinetic energy equals ½mv².' },
    category: 'mech',
    unit: 'J',
    condition: { zh: '物体由于运动而具有的能量；质量越大、速度越大，动能越大。', en: 'Energy of motion; larger mass or speed means more kinetic energy.' },
    pitfall: { zh: '动能与速度的平方成正比——速度翻倍，动能变为 4 倍。', en: 'Kinetic energy scales with v² — double the speed, quadruple the energy.' },
    usage: { zh: '限速原因、影响动能大小的因素探究。', en: 'Speed limits; factors affecting kinetic energy.' },
    chapter: '第十二章 机械能和内能',
  },
  {
    id: 'potential-energy',
    name: { zh: '重力势能', en: 'Gravitational potential energy' },
    formula: 'E_\\text{p} = mgh',
    label: { zh: '重力势能等于质量×重力常数×高度，Ep = mgh', en: 'Gravitational potential energy equals mgh.' },
    category: 'mech',
    unit: 'J',
    condition: { zh: '物体被举高而具有的能量；h 为相对参考面的高度。', en: 'Energy due to height above a reference level.' },
    pitfall: { zh: '高度是相对参考面（地面）的，参考面不同数值不同。', en: 'Height is relative to a chosen reference level.' },
    usage: { zh: '水电站蓄水、跳高、动能势能相互转化。', en: 'Hydroelectric dams, jumping, energy conversion.' },
    chapter: '第十二章 机械能和内能',
    relatedConstants: ['g'],
  },

  // ── 热学 ──
  {
    id: 'heat',
    name: { zh: '热量', en: 'Heat transfer' },
    formula: 'Q = cm\\Delta t',
    label: { zh: '物体吸收（放出）的热量 Q 等于比热容 c×质量 m×温度变化 Δt', en: 'Heat absorbed or released Q equals specific heat c × mass m × temperature change Δt.' },
    category: 'thermal',
    unit: 'J',
    condition: { zh: '温度变化 Δt = t末 − t初（吸热为正）；c 为物质的比热容。', en: 'Δt is the temperature change; c is the specific heat capacity.' },
    pitfall: { zh: '比热容是物质属性（水的 4.2×10³ J/(kg·°C) 最大）；升温/降温公式相同。', en: 'Specific heat is a material property; water has the largest common value.' },
    usage: { zh: '水的比热容大的应用（冷却剂、暖手宝）、热量计算。', en: 'Water as coolant, heat calculations.' },
    chapter: '第十二章 机械能和内能',
    relatedConstants: ['c水', 'c酒精', 'c冰'],
  },
  {
    id: 'fuel-heat',
    name: { zh: '燃料的热值', en: 'Fuel calorific value' },
    formula: 'Q_\\text{放} = mq',
    label: { zh: '燃料完全燃烧放出的热量等于质量×热值，Q放 = mq', en: 'Heat released by burning fuel equals mq.' },
    category: 'thermal',
    unit: 'J',
    condition: { zh: 'q 为燃料的热值（J/kg）；仅当燃料完全燃烧时适用。', en: 'q is the calorific value; assumes complete combustion.' },
    pitfall: { zh: '热值是燃料属性，与是否完全燃烧、质量多少无关。', en: 'Calorific value is intrinsic to the fuel.' },
    usage: { zh: '内燃机效率、能量转化计算。', en: 'Engine efficiency, energy conversion.' },
    chapter: '第十二章 机械能和内能',
  },

  // ── 光学 ──
  {
    id: 'lens',
    name: { zh: '透镜成像公式', en: 'Lens equation' },
    formula: '\\frac{1}{u} + \\frac{1}{v} = \\frac{1}{f}',
    label: { zh: '物距、像距、焦距满足 1/u + 1/v = 1/f', en: 'Object distance u, image distance v and focal length f satisfy 1/u + 1/v = 1/f.' },
    category: 'optics',
    unit: '—',
    condition: { zh: '凸透镜成实像时适用；u > 2f 成倒立缩小实像（照相机），f < u < 2f 成倒立放大实像（投影仪），u < f 成正立放大虚像（放大镜）。', en: 'Real images: u > 2f (camera), f < u < 2f (projector), u < f virtual (magnifier).' },
    pitfall: { zh: '实像倒立、虚像正立；虚像与物在透镜同侧，不能用光屏承接。', en: 'Real images are inverted; virtual images are upright and cannot be projected.' },
    usage: { zh: '照相机、投影仪、放大镜；近视/远视镜片选择。', en: 'Cameras, projectors, magnifiers, corrective lenses.' },
    chapter: '第三章 光的折射 透镜',
    diagram: { kind: 'lens' },
    labId: 'lens',
  },
  {
    id: 'wave-speed',
    name: { zh: '波速公式', en: 'Wave speed' },
    formula: 'c = \\lambda f',
    label: { zh: '波速等于波长乘以频率，c = λf；电磁波在真空中 c = 3×10⁸ m/s', en: 'Wave speed equals wavelength times frequency; EM waves travel at 3×10⁸ m/s in vacuum.' },
    category: 'optics',
    unit: 'm/s',
    condition: { zh: '适用于所有波（声波、光、电磁波）；真空中电磁波速恒定。', en: 'Applies to all waves; EM wave speed is constant in vacuum.' },
    pitfall: { zh: '频率由波源决定，波速由介质决定，波长随之变化。', en: 'Frequency comes from the source; speed from the medium.' },
    usage: { zh: '收音机调台、手机通信、光速测定。', en: 'Radio tuning, mobile communication, light speed.' },
    chapter: '第十七章 电磁波与现代通信',
    relatedConstants: ['c'],
  },

  // ── 声学 ──
  {
    id: 'frequency',
    name: { zh: '频率与周期', en: 'Frequency and period' },
    formula: 'f = \\frac{1}{T}',
    label: { zh: '频率等于周期的倒数，f = 1/T；单位 Hz', en: 'Frequency is the reciprocal of the period; unit Hz.' },
    category: 'sound',
    unit: 'Hz',
    condition: { zh: 'T 为完成一次全振动所需时间；人耳可听频率约 20–20000 Hz。', en: 'T is the time of one cycle; audible range ≈ 20–20000 Hz.' },
    pitfall: { zh: '频率决定音调：频率高音调高；响度由振幅决定。', en: 'Frequency sets pitch; amplitude sets loudness.' },
    usage: { zh: '音调高低判断、超声波/次声波应用。', en: 'Pitch, ultrasound and infrasound.' },
    chapter: '第一章 声现象',
  },
  {
    id: 'sound-wavelength',
    name: { zh: '声速与波长', en: 'Sound wavelength' },
    formula: 'v = \\lambda f',
    label: { zh: '声速等于波长乘以频率，v = λf', en: 'Sound speed equals wavelength times frequency.' },
    category: 'sound',
    unit: 'm/s',
    condition: { zh: '声音在空气中的速度约 340 m/s（15 ℃），与介质和温度有关。', en: 'Sound travels at about 340 m/s in air at 15 ℃.' },
    pitfall: { zh: '真空不能传声；声速与频率无关（同介质中）。', en: 'No sound in vacuum; speed is independent of frequency in a medium.' },
    usage: { zh: '回声测距、声呐、声音传播速度的应用。', en: 'Echo ranging, sonar.' },
    chapter: '第一章 声现象',
    relatedConstants: ['v声'],
  },

  // ── 电学 ──
  {
    id: 'ohms-law',
    name: { zh: '欧姆定律', en: "Ohm's law" },
    formula: 'I = \\frac{U}{R}',
    label: { zh: '导体中的电流与它两端的电压成正比，与它的电阻成反比，I = U/R', en: 'Current is proportional to voltage and inversely proportional to resistance.' },
    category: 'elec',
    unit: 'A',
    condition: { zh: '同一段导体（R 一定时）；变形公式 U = IR、R = U/I。', en: 'For the same conductor; rearranged as U = IR, R = U/I.' },
    pitfall: { zh: 'R 是导体属性，不随 U、I 改变（R = U/I 是计算式不是决定式）。', en: 'R is a property; R = U/I is a formula, not a definition.' },
    usage: { zh: '电路计算、伏安法测电阻、安全电压判断。', en: 'Circuit analysis, voltmeter-ammeter method, safety.' },
    chapter: '第十四章 欧姆定律',
    diagram: { kind: 'ohms-law' },
    relatedConstants: ['U'],
    labId: 'ohm',
  },
  {
    id: 'series-current',
    name: { zh: '串联电流规律', en: 'Series current' },
    formula: 'I = I_1 = I_2',
    label: { zh: '串联电路中电流处处相等，I = I₁ = I₂', en: 'Current is the same everywhere in a series circuit.' },
    category: 'elec',
    unit: 'A',
    condition: { zh: '串联电路中各用电器电流相等。', en: 'All components in series carry the same current.' },
    pitfall: { zh: '串联分压：电阻大的用电器分得电压大，与电流无关。', en: 'Series divides voltage; larger R gets larger U.' },
    usage: { zh: '串联电路分析、节日小彩灯。', en: 'Series analysis, string lights.' },
    chapter: '第十三章 简单电路',
    diagram: { kind: 'series' },
    labId: 'circuits',
  },
  {
    id: 'parallel-current',
    name: { zh: '并联电流规律', en: 'Parallel current' },
    formula: 'I = I_1 + I_2',
    label: { zh: '并联电路干路电流等于各支路电流之和，I = I₁ + I₂', en: 'Total current equals the sum of branch currents.' },
    category: 'elec',
    unit: 'A',
    condition: { zh: '并联电路中干路电流等于支路电流之和。', en: 'Branch currents add up to the total in parallel.' },
    pitfall: { zh: '并联分流：电阻小的支路电流大。', en: 'Parallel divides current; smaller R carries more current.' },
    usage: { zh: '家庭电路分析、并联电路电流计算。', en: 'Household wiring, parallel current calculations.' },
    chapter: '第十三章 简单电路',
    diagram: { kind: 'parallel' },
    labId: 'circuits',
  },
  {
    id: 'series-voltage',
    name: { zh: '串联电压规律', en: 'Series voltage' },
    formula: 'U = U_1 + U_2',
    label: { zh: '串联电路总电压等于各部分电压之和，U = U₁ + U₂', en: 'Total voltage equals the sum of component voltages in series.' },
    category: 'elec',
    unit: 'V',
    condition: { zh: '串联电路中电源电压分配在各用电器上。', en: 'Supply voltage is divided among series components.' },
    pitfall: { zh: '串联分压与电阻成正比：U₁/U₂ = R₁/R₂。', en: 'Voltage divides in proportion to resistance.' },
    usage: { zh: '串联电路电压计算、分压电路。', en: 'Series voltage calculations, voltage dividers.' },
    chapter: '第十三章 简单电路',
    labId: 'circuits',
  },
  {
    id: 'parallel-voltage',
    name: { zh: '并联电压规律', en: 'Parallel voltage' },
    formula: 'U = U_1 = U_2',
    label: { zh: '并联电路各支路两端电压相等，U = U₁ = U₂', en: 'All parallel branches share the same voltage.' },
    category: 'elec',
    unit: 'V',
    condition: { zh: '并联电路中各支路电压等于电源电压。', en: 'Each branch sees the supply voltage in parallel.' },
    pitfall: { zh: '并联各支路互不影响：一条支路断开，其他支路仍工作。', en: 'Branches are independent; one open branch does not stop others.' },
    usage: { zh: '家庭电路电压分析。', en: 'Household circuits.' },
    chapter: '第十三章 简单电路',
    labId: 'circuits',
  },
  {
    id: 'series-resistance',
    name: { zh: '串联电阻规律', en: 'Series resistance' },
    formula: 'R = R_1 + R_2',
    label: { zh: '串联电路总电阻等于各电阻之和，R = R₁ + R₂', en: 'Total series resistance is the sum.' },
    category: 'elec',
    unit: 'Ω',
    condition: { zh: '串联电路等效电阻大于任何一个分电阻。', en: 'The equivalent resistance exceeds every individual one.' },
    pitfall: { zh: '串联总电阻比每个都大（相当于导线变长）。', en: 'Series resistance grows like lengthening the wire.' },
    usage: { zh: '串联电路总电阻计算、限流电阻选择。', en: 'Total resistance, current-limiting resistors.' },
    chapter: '第十四章 欧姆定律',
  },
  {
    id: 'parallel-resistance',
    name: { zh: '并联电阻规律', en: 'Parallel resistance' },
    formula: '\\frac{1}{R} = \\frac{1}{R_1} + \\frac{1}{R_2}',
    label: { zh: '并联电路总电阻的倒数等于各电阻倒数之和，1/R = 1/R₁ + 1/R₂', en: 'The reciprocal of total parallel resistance sums the reciprocals.' },
    category: 'elec',
    unit: 'Ω',
    condition: { zh: '并联电路等效电阻小于任何一个分电阻。', en: 'The equivalent resistance is smaller than each branch.' },
    pitfall: { zh: '并联总电阻比每个都小（相当于导线变粗）；两个等值电阻并联为 R/2。', en: 'Parallel resistance shrinks; two equal R in parallel give R/2.' },
    usage: { zh: '并联电路总电阻计算、家庭电路电阻分析。', en: 'Parallel totals, household wiring.' },
    chapter: '第十四章 欧姆定律',
  },
  {
    id: 'electric-work',
    name: { zh: '电功', en: 'Electric work' },
    formula: 'W = UIt',
    label: { zh: '电功等于电压×电流×时间，W = UIt；单位 1 kW·h = 3.6×10⁶ J', en: 'Electric work equals UIt; 1 kW·h = 3.6×10⁶ J.' },
    category: 'elec',
    unit: 'J',
    condition: { zh: '电流做功（电能转化为其他形式能）的多少；纯电阻电路可化为 W = I²Rt = U²t/R。', en: 'Work done by current; for pure resistors W = I²Rt = U²t/R.' },
    pitfall: { zh: '电功与电热：纯电阻电路相等，非纯电阻（电动机）电功 > 电热。', en: 'For motors, electric work exceeds heat; equal only for pure resistors.' },
    usage: { zh: '电能表读数、电费计算。', en: 'Energy meters, electricity bills.' },
    chapter: '第十五章 电功和电热',
    relatedConstants: ['U'],
  },
  {
    id: 'electric-power',
    name: { zh: '电功率', en: 'Electric power' },
    formula: 'P = UI',
    label: { zh: '电功率等于电压乘以电流，P = UI；纯电阻电路 P = I²R = U²/R', en: 'Electric power equals UI; for pure resistors P = I²R = U²/R.' },
    category: 'elec',
    unit: 'W',
    condition: { zh: '用电器单位时间消耗的电能；额定功率 vs 实际功率。', en: 'Energy per unit time; rated vs actual power.' },
    pitfall: { zh: '灯泡亮度由实际功率决定，不是额定功率；220V 100W 灯泡电阻 = U²/P。', en: 'Brightness follows actual power; R = U²/P for a rated bulb.' },
    usage: { zh: '用电器铭牌、家庭电路功率计算、节能比较。', en: 'Nameplates, household power, energy saving.' },
    chapter: '第十五章 电功和电热',
    relatedConstants: ['U'],
  },
  {
    id: 'joule-law',
    name: { zh: '焦耳定律', en: "Joule's law" },
    formula: 'Q = I^2 R t',
    label: { zh: '电流通过导体产生的热量等于电流平方×电阻×时间，Q = I²Rt', en: 'Heat generated by current equals I²Rt.' },
    category: 'elec',
    unit: 'J',
    condition: { zh: '电流的热效应；电热器（电炉、电饭锅）工作原理。', en: 'Heating effect; electric heaters work this way.' },
    pitfall: { zh: '电热与电流平方成正比——电流翻倍，热量变 4 倍；与通电时间成正比。', en: 'Heat scales with I² — double the current, quadruple the heat.' },
    usage: { zh: '电热器、保险丝熔断原理、防止电热危害。', en: 'Heaters, fuses, heat hazards.' },
    chapter: '第十五章 电功和电热',
  },
];
